# Generated by Django 3.1.3 on 2020-11-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='mber')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('content', models.CharField(max_length=200, verbose_name='content')),
                ('timestamp', models.DateField(auto_now=True, verbose_name='time')),
            ],
            options={
                'verbose_name': 'information table',
                'verbose_name_plural': 'information table',
            },
        ),
    ]
